name: CI devops 2025
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
